# Generated by Django 2.1.1 on 2019-10-02 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('company_tin', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=50, unique=True)),
                ('sss', models.CharField(max_length=50, unique=True)),
                ('pagibig', models.CharField(max_length=50, unique=True)),
                ('philhealth', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('mobile_no', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('contact', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default='lloyd.garcia', on_delete=django.db.models.deletion.CASCADE, related_name='profile_to_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personalbenefits',
            name='pers_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits_to_profile_fk', to='payrollsystemapp.ProfileInfo'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='comp_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_to_profile_fk', to='payrollsystemapp.ProfileInfo'),
        ),
    ]
