# Generated by Django 2.1.1 on 2019-10-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollsystemapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='contact',
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='mobile_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
