# Generated by Django 2.1.1 on 2019-10-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollsystemapp', '0002_auto_20191002_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='suffix',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
