# Generated by Django 2.1.1 on 2019-10-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollsystemapp', '0003_auto_20191003_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='suffix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
