# Generated by Django 2.1.1 on 2019-10-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollsystemapp', '0004_auto_20191003_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_cut_off_period_from', models.DateField()),
                ('payroll_cut_off_period_to', models.DateField()),
                ('payroll_date', models.DateField()),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('legal_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('special_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('late_or_absences', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('salary_or_cash_advance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sss_premiums', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('philhealth_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pagibig_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pagibig_loan', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_employee_fk', to='payrollsystemapp.ProfileInfo')),
            ],
        ),
    ]
