# Generated by Django 2.1.1 on 2019-10-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollsystemapp', '0005_employeepayroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
